```{r}


library(readr)
library(janitor)
library(ggplot2)

english = read.table("data/jennifer_english.TABLE", header = FALSE, sep = ",")
spanish = read.table("data/jennifer_spanish.TABLE", header = FALSE, sep = ",")
french = read.table("data/jennifer_french.TABLE", header = FALSE, sep = ",")

english = english %>%
  row_to_names(row_number = 1)  

spanish = spanish %>%
  row_to_names(row_number = 1)

french = french %>%
  row_to_names(row_number = 1)

english$language = "english"
spanish$language = "spanish"
french$language = "french"


english = transform(english, tmax = as.numeric(tmax))
english = transform(english, tmin = as.numeric(tmin))

english$vot = english$tmax - english$tmin

spanish = transform(spanish, tmax = as.numeric(tmax))
spanish = transform(spanish, tmin = as.numeric(tmin))

spanish$vot = spanish$tmax - spanish$tmin

french = transform(french, tmax = as.numeric(tmax))
french = transform(french, tmin = as.numeric(tmin))

french$vot = french$tmax - french$tmin

engvot = mean(english$vot)

spgvot = mean(spanish$vot)

frgvot = mean(french$vot)

t.test(english$vot, spanish$vot)
t.test(spanish$vot, french$vot)
t.test(english$vot, french$vot)
all = rbind(english,french,spanish)

ggplot(all, aes (x = language, y = vot)) + geom_boxplot(color = "black", fill = "seagreen3")

ggplot(all, aes (x = language, y = vot)) + geom_point()

all %>% 
  select(language, vot) %>% 
  pivot_wider(names_from = language, values_from = vot)

%>% 
  pivot_wider(names_from = language, values_from = vot)


```

Descriptives 

```{r}

all2 = all %>% 
  group_by(language) %>% 
  summarise(mean = mean(vot), sd = sd(vot)) %>% 
  mutate(participant = "jennifer")

all2 %>% 
  write.csv("tidy_data/jennifer.csv")

```